spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: service-consumer-demo
#        tags: dev
#        health-check-path: /health
#        health-check-interval: 15s
        register: false #设置不需要注册到 consul 中
#        instance-id: app
server:
  port: 8905