spring:
  application:
    name: consul-producer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: service-producer-demo
#        tags: dev
#        health-check-path: /health
#        health-check-interval: 15s
#        instance-id: app
server:
  port: 8903


# 启动命令
# windows consul agent -dev
#

#config/consul-producer,dev/data
#myName: jack